from __future__ import annotations

import base64
import json

from app.adapters.drive_client import DriveClient
from app.adapters.gmail_client import GmailClient
from app.adapters.llm_client import LLMClient
from app.config import Settings
from app.services.cost_service import CostService
from app.schemas.common import ReviewItem
from app.schemas.email import AttachmentLink, EmailAnalysis, EmailMessage, EmailTaskItem
from app.utils.confidence import build_confidence


class EmailAnalysisService:
    """AI extraction boundary.

    Replace the internals with a real LLM call later. The rest of the workflow can stay stable.
    """

    def __init__(
        self,
        llm_client: LLMClient | None = None,
        settings: Settings | None = None,
        cost_service: CostService | None = None,
    ):
        self.llm = llm_client
        self.settings = settings
        self.cost_service = cost_service

    def analyze_email(self, email: EmailMessage) -> EmailAnalysis:
        if self.llm and self.settings and self.settings.llm.enabled and self.settings.llm.use_for_email_analysis:
            try:
                return self._analyze_with_llm(email)
            except Exception:
                pass
        return self._analyze_heuristic(email)

    def _analyze_with_llm(self, email: EmailMessage) -> EmailAnalysis:
        assert self.llm is not None
        assert self.settings is not None
        system_prompt = (
            "You extract structured productivity actions from emails. "
            "Return strict JSON with keys: summary, outline (array of strings), "
            "action_items (array of strings), events (array of strings), suggested_title, "
            "suggested_project_name, suggested_contexts (array), suggested_importance (int), "
            "suggested_time_required (int), event_start_iso, event_end_iso, event_location, event_description, rationale (array)."
        )
        user_prompt = json.dumps(
            {
                "email_id": email.id,
                "subject": email.subject,
                "sender": email.sender,
                "body": email.body,
            }
        )
        data = self.llm.chat_json(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            model=self._model_for_email_analysis(),
            operation="email_analysis",
            metadata={"email_id": email.id},
        )
        action_items = [EmailTaskItem(text=item) for item in (data.get("action_items") or [])]
        return EmailAnalysis(
            email_id=email.id,
            summary=(data.get("summary") or email.subject)[:500],
            outline=list(data.get("outline") or []),
            action_items=action_items,
            event_hints=list(data.get("events") or []),
            suggested_title=data.get("suggested_title") or email.subject,
            suggested_status="Inbox",
            suggested_importance=int(data.get("suggested_importance") or 50),
            suggested_contexts=list(data.get("suggested_contexts") or ["Computer"]),
            suggested_time_required=int(data.get("suggested_time_required") or 30),
            suggested_project_name=data.get("suggested_project_name"),
            event_start=data.get("event_start_iso"),
            event_end=data.get("event_end_iso"),
            event_location=data.get("event_location"),
            event_description=data.get("event_description"),
            rationale=list(data.get("rationale") or ["Generated by standard-tier LLM email analysis."]),
            confidence=build_confidence(0.86 if action_items else 0.7, "LLM extracted summary and actions.", False),
        )

    def _model_for_email_analysis(self) -> str:
        assert self.settings is not None
        tier = self.settings.llm.email_analysis_tier
        if self.cost_service:
            return self.cost_service.get_tier_model(tier)
        if tier == "fast":
            return self.settings.llm.cheap_model
        if tier == "balanced":
            return self.settings.llm.standard_model
        if tier == "smart":
            return self.settings.llm.premium_model
        return self.settings.llm.best_model or self.settings.llm.premium_model

    def _analyze_heuristic(self, email: EmailMessage) -> EmailAnalysis:
        body = email.body.strip()
        lines = [line.strip(" -*\t") for line in body.splitlines() if line.strip()]
        summary = lines[0][:280] if lines else email.subject
        action_lines = [line for line in lines if any(token in line.lower() for token in ["please", "todo", "action", "follow up", "need to", "reply", "send", "schedule"])]
        event_lines = [line for line in lines if any(token in line.lower() for token in ["meeting", "call", "calendar", "zoom", "tomorrow", "at ", "schedule"])][:5]
        if not action_lines and lines:
            action_lines = lines[: min(3, len(lines))]

        contexts: list[str] = []
        lower = f"{email.subject} {email.body}".lower()
        if any(token in lower for token in ["computer", "email", "online", "document", "spreadsheet"]):
            contexts.append("Computer")
        if any(token in lower for token in ["call", "phone", "voicemail"]):
            contexts.append("Phone")
        if not contexts:
            contexts.append("Computer")

        importance = 100 if any(token in lower for token in ["urgent", "asap", "important", "deadline"]) else 50
        estimated_minutes = 15 if len(action_lines) <= 1 else 30 if len(action_lines) <= 3 else 45
        rationale = [
            "Generated a summary from the most salient email lines.",
            "Extracted action items using deterministic heuristics behind an AI-analysis service boundary.",
            "Assigned default Computer context when no clearer context was found.",
        ]
        return EmailAnalysis(
            email_id=email.id,
            summary=summary,
            outline=lines[:5],
            action_items=[EmailTaskItem(text=item) for item in action_lines],
            event_hints=event_lines,
            suggested_title=email.subject,
            suggested_status="Inbox",
            suggested_importance=importance,
            suggested_contexts=contexts,
            suggested_time_required=estimated_minutes,
            suggested_project_name=email.subject.split(":")[0].strip() if ":" in email.subject else None,
            event_start=None,
            event_end=None,
            event_location="Virtual" if any(token in lower for token in ["zoom", "meet", "teams"]) else None,
            event_description=summary,
            rationale=rationale,
            confidence=build_confidence(0.78 if action_lines else 0.62, "Email analysis generated for task structuring.", not bool(action_lines)),
        )


class EmailService:
    def __init__(
        self,
        gmail_client: GmailClient,
        settings: Settings,
        analysis_service: EmailAnalysisService | None = None,
        drive_client: DriveClient | None = None,
    ):
        self.gmail = gmail_client
        self.settings = settings
        self.analysis_service = analysis_service or EmailAnalysisService(settings=settings)
        self.drive = drive_client

    def get_unprocessed_tagged_emails(self, max_count: int, query: str | None = None) -> list[EmailMessage]:
        return self.gmail.list_tagged_messages(query or self.settings.gmail.label_query, max_count)

    def mark_email_processed(self, email_id: str) -> None:
        self.gmail.mark_processed(email_id, self.settings.gmail.processed_label)

    def analyze_email(self, email: EmailMessage) -> EmailAnalysis:
        return self.analysis_service.analyze_email(email)

    def process_attachments(self, email: EmailMessage, preview_only: bool) -> tuple[list[AttachmentLink], list[ReviewItem]]:
        cfg = self.settings.attachments
        if cfg.mode == "none" or not email.attachments:
            return [], []

        links: list[AttachmentLink] = []
        review_items: list[ReviewItem] = []
        max_bytes = cfg.max_attachment_size_mb * 1024 * 1024
        for attachment in email.attachments[: cfg.max_attachments_per_email]:
            if attachment.size_bytes > max_bytes:
                review_items.append(
                    ReviewItem(
                        item_type="attachment_size",
                        reason=f"Attachment '{attachment.filename}' exceeds configured max size.",
                        options=[{"filename": attachment.filename, "size_bytes": attachment.size_bytes}],
                        confidence=build_confidence(0.3, "Attachment needs manual handling due to size.", True),
                    )
                )
                continue

            if cfg.mode == "notion_file":
                review_items.append(
                    ReviewItem(
                        item_type="attachment_mode",
                        reason="Notion file uploads are not implemented yet; using review path.",
                        options=[{"filename": attachment.filename, "mode": "notion_file"}],
                        confidence=build_confidence(0.5, "Switch to drive_link mode for automated upload.", True),
                    )
                )
                links.append(
                    AttachmentLink(
                        filename=attachment.filename,
                        mime_type=attachment.mime_type,
                        size_bytes=attachment.size_bytes,
                    )
                )
                continue

            if cfg.mode == "drive_link":
                if preview_only:
                    links.append(
                        AttachmentLink(
                            filename=attachment.filename,
                            mime_type=attachment.mime_type,
                            size_bytes=attachment.size_bytes,
                            drive_url=f"preview://drive-upload/{attachment.filename}",
                        )
                    )
                    continue

                if not attachment.content_b64:
                    review_items.append(
                        ReviewItem(
                            item_type="attachment_content",
                            reason=f"Attachment '{attachment.filename}' did not include content bytes.",
                            options=[{"filename": attachment.filename}],
                            confidence=build_confidence(0.35, "Attachment upload skipped due to missing content.", True),
                        )
                    )
                    continue

                if not self.drive:
                    review_items.append(
                        ReviewItem(
                            item_type="attachment_drive",
                            reason="Drive client not configured; cannot upload attachments.",
                            options=[{"filename": attachment.filename}],
                            confidence=build_confidence(0.2, "Configure Drive client for attachment uploads.", True),
                        )
                    )
                    continue

                content = base64.b64decode(attachment.content_b64.encode("utf-8"))
                uploaded = self.drive.upload_bytes(
                    filename=attachment.filename,
                    mime_type=attachment.mime_type,
                    content=content,
                    folder_id=cfg.drive_folder_id,
                )
                links.append(
                    AttachmentLink(
                        filename=attachment.filename,
                        mime_type=attachment.mime_type,
                        size_bytes=attachment.size_bytes,
                        drive_file_id=uploaded.get("id"),
                        drive_url=uploaded.get("webViewLink") or uploaded.get("webContentLink"),
                    )
                )

        return links, review_items
